# cos6-specific because of PYTHON_SYSCONFIGDATA_NAME below.  Would be nice to make that more generic if possible.
ctng_target_platform:
  - linux-64
FINAL_CPPFLAGS:
  - -DNDEBUG -D_FORTIFY_SOURCE=2 -O2
FINAL_CFLAGS:
  - -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_CXXFLAGS:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_FFLAGS:
  - -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_LDFLAGS:
  - -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags
FINAL_DEBUG_CPPFLAGS:
  - -D_DEBUG -D_FORTIFY_SOURCE=2 -Og
FINAL_DEBUG_CFLAGS:
  - -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_CXXFLAGS:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_FFLAGS:
  - -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -pipe
FINAL_CONDA_PYTHON_SYSCONFIGDATA_NAME:
  - _sysconfigdata_x86_64_conda_cos6_linux_gnu
